name: Push to docker.io

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Docker Hub Username'
        required: true
      password:
        description: 'Docker Hub Password'
        required: true
        type: string
      image_name:
        description: 'Docker Image Name'
        required: true
      amd64_only:
        description: 'Build only for amd64'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ inputs.amd64_only == false }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ inputs.amd64_only == false }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker.io
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: latest
          images: ${{ inputs.username }}/${{ inputs.image_name }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          provenance: false
          platforms: ${{ inputs.amd64_only == true && 'linux/amd64' || 'linux/arm64,linux/amd64' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
